spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER:nacos:8848}
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:nacos}

aliyun:
  oss:
    endpoint: ${OSS_ENDPOINT}
    access-key-id: ${OSS_ACCESSKEY_ID}
    access-key-secret: ${OSS_ACCESSKEY_SECRET}
    bucket: ${OSS_BUCKET}
